Fix

diff --git a/.azure-pipelines/build-mac.yaml b/.azure-pipelines/build-mac.yaml
--- a/.azure-pipelines/build-mac.yaml
+++ b/.azure-pipelines/build-mac.yaml
@@ -31,8 +31,15 @@ jobs:
     displayName: 'Configure and build'
 
   - script: |
-      export QT_QPA_PLATFORM=offscreen
-      export TEST_OUTPUT_ON_FAILURE=1
+      Xvfb :99 &
+      export DISPLAY=:99
+      sleep 3
       cd build
-      ninja test
+      ctest
+      tests_pass=$?
+      if [ $tests_pass -ne 0 ]; then
+          echo "\n\n\nTests failed, rerunning with verbose output"
+          ctest --rerun-failed --output-on-failure
+      fi
+      exit $tests_pass
     displayName: 'Run tests'
