d

diff --git a/.github/workflows/build-ubuntu.yml b/.github/workflows/build-ubuntu.yml
--- a/.github/workflows/build-ubuntu.yml
+++ b/.github/workflows/build-ubuntu.yml
@@ -92,12 +92,31 @@ jobs:
     steps:
       - uses: actions/checkout@v4
 
-      - uses: actions/cache@v4
-        id: cache-builds
+      - name: Check code format
+        if: matrix.config.checkCodeFormat
+        run: |
+          set +x -euo pipefail
+          python -m pip install ruff==0.15.0 clang-format==21.1.8
+          ./scripts/format/c++.sh
+          ./scripts/format/python.sh
+          git diff --name-only
+          git diff --exit-code || (echo "Code formatting failed" && exit 1)
+
+      - name: Restore Compiler cache
+        uses: actions/cache@v4
+        id: cache-compiler
         with:
           key: v${{ env.COMPILER_CACHE_VERSION }}-${{ matrix.config.os }}-${{ matrix.config.cmakeBuildType }}-${{ matrix.config.asanEnabled }}--${{ matrix.config.cudaEnabled }}-${{ github.run_id }}-${{ github.run_number }}
           restore-keys: v${{ env.COMPILER_CACHE_VERSION }}-${{ matrix.config.os }}-${{ matrix.config.cmakeBuildType }}-${{ matrix.config.asanEnabled }}--${{ matrix.config.cudaEnabled }}
           path: ${{ env.COMPILER_CACHE_DIR }}
+
+      - name: Restore FetchContent cache
+        uses: actions/cache@v4
+        id: cache-fetchcontent
+        with:
+          key: fetchcontent-v${{ env.FETCHCONTENT_CACHE_VERSION }}-${{ matrix.config.os }}-cuda_${{ matrix.config.cudaEnabled }}-${{ hashFiles('cmake/FindDependencies.cmake', 'src/thirdparty/CMakeLists.txt') }}
+          restore-keys: fetchcontent-v${{ env.FETCHCONTENT_CACHE_VERSION }}-${{ matrix.config.os }}-cuda_${{ matrix.config.cudaEnabled }}-
+          path: ${{ env.FETCHCONTENT_CACHE_DIR }}
 
       - name: Install compiler cache
         run: |
@@ -119,16 +138,6 @@ jobs:
           echo "108b087f156a9fe7da0c796de1ef73f5855d2a33a27983769ea39061359a40fc  ${ctcache_commit_id}.zip" | sha256sum --check
           unzip "${ctcache_commit_id}.zip"
           mv ctcache-${ctcache_commit_id}/clang-tidy* "$COMPILER_CACHE_DIR/bin"
-
-      - name: Check code format
-        if: matrix.config.checkCodeFormat
-        run: |
-          set +x -euo pipefail
-          python -m pip install ruff==0.15.0 clang-format==21.1.8
-          ./scripts/format/c++.sh
-          ./scripts/format/python.sh
-          git diff --name-only
-          git diff --exit-code || (echo "Code formatting failed" && exit 1)
 
       - name: Setup Ubuntu
         run: |
@@ -196,14 +205,6 @@ jobs:
           if [ "${{ matrix.config.coverageEnabled }}" == "true" ]; then
             sudo apt-get install -y gcovr
           fi
-
-      - name: FetchContent cache
-        uses: actions/cache@v4
-        id: cache-fetchcontent
-        with:
-          key: fetchcontent-v${{ env.FETCHCONTENT_CACHE_VERSION }}-${{ matrix.config.os }}-cuda_${{ matrix.config.cudaEnabled }}-${{ hashFiles('cmake/FindDependencies.cmake', 'src/thirdparty/CMakeLists.txt') }}
-          restore-keys: fetchcontent-v${{ env.FETCHCONTENT_CACHE_VERSION }}-${{ matrix.config.os }}-cuda_${{ matrix.config.cudaEnabled }}-
-          path: ${{ env.FETCHCONTENT_CACHE_DIR }}
 
       - name: Configure and build
         run: |
